language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls"
services:
  - "mysql"
script:
  - "coverage run --source=repo_health manage.py test"
after_success:
  - "coveralls"