# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhFork',
            fields=[
                ('fork_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('ext_ref_id', models.CharField(max_length=24)),
            ],
            options={
                'db_table': 'forks',
                'managed': False,
                'verbose_name': 'GitHub Fork',
            },
        ),
        migrations.CreateModel(
            name='GhProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('ext_ref_id', models.CharField(max_length=24)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
                'verbose_name': 'GitHub Project',
            },
        ),
        migrations.CreateModel(
            name='GhProjectCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'project_commits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GhRepoLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('ext_ref_id', models.CharField(max_length=24)),
            ],
            options={
                'db_table': 'repo_labels',
                'managed': False,
                'verbose_name': 'GitHub Repo Label',
            },
        ),
        migrations.CreateModel(
            name='GhRepoMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('ext_ref_id', models.CharField(max_length=24)),
            ],
            options={
                'db_table': 'repo_milestones',
                'managed': False,
                'verbose_name': 'GitHub Repo Milestone',
            },
        ),
    ]
