# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhFork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fork_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField()),
                ('ext_ref_id', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name': 'GitHub Fork',
                'managed': False,
                'db_table': 'forks',
            },
        ),
        migrations.CreateModel(
            name='GhProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('ext_ref_id', models.CharField(max_length=24)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'verbose_name': 'GitHub Project',
                'managed': False,
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='GhProjectCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'project_commits',
            },
        ),
        migrations.CreateModel(
            name='GhRepoLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('ext_ref_id', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name': 'GitHub Repo Label',
                'managed': False,
                'db_table': 'repo_labels',
            },
        ),
        migrations.CreateModel(
            name='GhRepoMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('ext_ref_id', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name': 'GitHub Repo Milestone',
                'managed': False,
                'db_table': 'repo_milestones',
            },
        ),
    ]
