# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('created_at', models.DateTimeField()),
                ('ext_ref_id', models.CharField(max_length=24)),
            ],
            options={
                'managed': False,
                'db_table': 'commits',
                'verbose_name': 'GitHub Commit',
            },
        ),
        migrations.CreateModel(
            name='GhCommitComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=256, null=True)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('comment_id', models.IntegerField(unique=True)),
                ('ext_ref_id', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'commit_comments',
                'verbose_name': 'GitHub Commit Comment',
            },
        ),
        migrations.CreateModel(
            name='GhCommitParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'commit_parents',
            },
        ),
    ]
