# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('ext_ref_id', models.CharField(default='0', max_length=24)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'GitHub User',
                'db_table': 'users',
            },
        ),
    ]
