# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhFollower',
            fields=[
                ('created_at', models.DateTimeField()),
                ('ext_ref_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'GitHub Follower',
                'db_table': 'followers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GhOrgMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'GitHub Organization Member',
                'db_table': 'organization_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GhProjectMember',
            fields=[
                ('created_at', models.DateTimeField()),
                ('ext_ref_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'GitHub Project Member',
                'db_table': 'project_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GhUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('ext_ref_id', models.CharField(max_length=24)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'GitHub User',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GhWatcher',
            fields=[
                ('created_at', models.DateTimeField()),
                ('ext_ref_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'GitHub Watcher',
                'db_table': 'watchers',
                'managed': False,
            },
        ),
    ]
